Dht
Derovi/dismess pull request #11
Opened 2021-04-08 22:17 UTC by buyval01

2021-04-09 11:07 UTC, IgorFilipovich requested changes

2021-04-09 11:07 UTC, IgorFilipovich commented on src/main/kotlin/by/dismess/core/dht/DHT.kt
> +    fun saveUser(userId: UserID, address: InetSocketAddress)
Убрать функцию из интерфейса и сделать приватной

2021-04-09 11:07 UTC, IgorFilipovich commented on src/main/kotlin/by/dismess/core/dht/DHTImpl.kt
> +        if (ownerId.rawID inBucket bucket) {
Мб in?

2021-04-09 11:07 UTC, IgorFilipovich commented on src/main/kotlin/by/dismess/core/dht/DHTImpl.kt
> +        }
Кажется это лучше делать раз в какое-то время, а не при каждом поиске

2021-04-09 11:07 UTC, IgorFilipovich commented on src/main/kotlin/by/dismess/core/dht/DHTImpl.kt
> +        }
Сделать добавление, если в бакете есть место

2021-04-09 11:07 UTC, IgorFilipovich commented on src/main/kotlin/by/dismess/core/dht/DHTImpl.kt
> +        }
Можно изменить нахождение без сортировок и постоянного пересчета количества

2021-04-09 11:07 UTC, IgorFilipovich commented on src/main/kotlin/by/dismess/core/dht/DHTImpl.kt
> +        listOfNodes.map { foundedNodes[TODO("Cast it.key, that has BitInteger type, to UserID")] = it.value }
Мб есть что-то стандартное

2021-04-11 22:54 UTC, buyval01 commented on src/main/kotlin/by/dismess/core/dht/DHTImpl.kt
> +        if (ownerId.rawID inBucket bucket) {
`in` является ключевым словом, поэтому сделать соответсвующую инфиксную функцию нельзя

2021-04-11 22:57 UTC, buyval01 commented on src/main/kotlin/by/dismess/core/dht/DHTImpl.kt
> +        }
Согласен с замечанием

2021-04-11 22:58 UTC, buyval01 commented on src/main/kotlin/by/dismess/core/dht/DHTImpl.kt
> +        }
Изменения внесены в последнем коммите

2021-04-11 23:01 UTC, buyval01 commented on src/main/kotlin/by/dismess/core/dht/DHTImpl.kt
> +        }
Но тогда надо определится когда, помимо процесса поиска, мы будем запоминать новых пользователей. 
Кажется, что мы обязаны как минимум пару раз до первого поиска это сделать, т.к. иначе нам негде будет искать :)

2021-04-11 23:08 UTC, buyval01 commented on src/main/kotlin/by/dismess/core/dht/DHT.kt
> +    fun saveUser(userId: UserID, address: InetSocketAddress)
Сделано!

2021-04-11 23:17 UTC, buyval01 commented on src/main/kotlin/by/dismess/core/dht/DHTImpl.kt
> +        }
Благодарю за идею. И правда получилось избавиться от сортировки, но вот с пересчетом количества непонятно, т.к. нам же надо контролировать момент, когда мы наберем достаточное количество вершин на расстоянии `< maxDistance`.

2021-04-12 18:08 UTC, IgorFilipovich commented on src/main/kotlin/by/dismess/core/dht/DHTImpl.kt
> +        }
Кажется это происходит при регистрации пользователя в сеть, когда он получает таблицу от пригласившего его пользователя

2021-04-12 18:42 UTC, IgorFilipovich requested changes

2021-04-12 18:42 UTC, IgorFilipovich commented on src/main/kotlin/by/dismess/core/dht/DHTImpl.kt
> +        if (ownerId.rawID inBucket bucket && bucket.idToIP.size > BUCKET_SIZE) {
Не проверяется случай, когда бакет заполнен, но ownerId.rawID not in bucket

2021-04-12 18:42 UTC, IgorFilipovich commented on src/main/kotlin/by/dismess/core/dht/DHTImpl.kt
>      private val ownerId: UserID = TODO()
Такие сокращения лучше называть большими буквами, т.е. ownerID

2021-04-12 18:42 UTC, IgorFilipovich commented on src/main/kotlin/by/dismess/core/dht/DHTImpl.kt
> +    private fun getBucket(userId: UserID): Bucket {
Аналогично userID

2021-04-12 18:42 UTC, IgorFilipovich commented on src/main/kotlin/by/dismess/core/dht/DHTImpl.kt
> +            }
Не уверен как работают итераторы и in в Kotlin, но возможно это вечный цикл, т.к. происходит вставка в лист при итерации по листу.

2021-04-12 18:42 UTC, IgorFilipovich commented on src/main/kotlin/by/dismess/core/dht/DHTImpl.kt
> +        } while (listOfNodes.size < count)
И в принципе кажется лучше завести 2 отдельных листа/массива, один для уже нужных, достаточно близких нод, другой для запросов. Код может получится и чуть длиннее, хотя не факт, но зато не будет постоянных  вставок/фильтров/удалений в один массив, плюс код получится понятнее

2021-05-03 09:16 UTC, IgorFilipovich requested changes

2021-05-03 09:16 UTC, IgorFilipovich commented on src/main/kotlin/by/dismess/core/dht/DHTImpl.kt
> +        networkService.registerPost("DHT/Ping") {}
Почему пинг это Post запрос?

2021-05-03 09:16 UTC, IgorFilipovich commented on src/main/kotlin/by/dismess/core/dht/DHTImpl.kt
> +            tryToSaveUser(request!!.sender, message.sender)
Это здесь еще нужна проверка на null?

2021-05-03 09:16 UTC, IgorFilipovich commented on src/main/kotlin/by/dismess/core/dht/DHTImpl.kt
> +            }
Уверен, что каждый раз производить проверку выгодно?
Мб делать это раз в какое-то время, а в случае, когда не можем добавить чувака просто забить?

2021-05-03 09:16 UTC, IgorFilipovich commented on src/main/kotlin/by/dismess/core/dht/DHTImpl.kt
> +    private suspend fun tryToSaveUser(userId: UserID, address: InetSocketAddress) {
Не люблю названия с приколами вроде To, мб просто trySaveUser, англ конечно не C3, но выглядит лучше

2021-05-03 09:16 UTC, IgorFilipovich commented on src/main/kotlin/by/dismess/core/dht/DHTImpl.kt
> +    private fun getBucketWithUser(userId: UserID): Bucket {
Аналогично To, предлагаю getUserBucket

2021-05-03 09:16 UTC, IgorFilipovich commented on src/main/kotlin/by/dismess/core/dht/DHTImpl.kt
> +            usersTable.remove(bucket)
Может вынести процедуру деления в отдельную функцию?
А то как-то много

2021-05-03 09:16 UTC, IgorFilipovich commented on src/main/kotlin/by/dismess/core/dht/DHTImpl.kt
> +            }
Аналогично хочется вынести в отдельную функцию чистки  ̶т̶р̶у̶б̶, бакета.

2021-05-03 09:16 UTC, IgorFilipovich commented on src/main/kotlin/by/dismess/core/dht/DHTImpl.kt
> +            }
Для чего этот иф?

2021-05-03 09:16 UTC, IgorFilipovich commented on src/main/kotlin/by/dismess/core/dht/DHTImpl.kt
> +    private fun getBucketWithUser(userId: UserID): Bucket {
И кажется не котлин-стайл функция, такие функции нужно делать через =

2021-05-03 09:16 UTC, IgorFilipovich commented on src/main/kotlin/by/dismess/core/dht/DHTImpl.kt
> +        while (findIterations < 100 || usersBuffer.size > 1) {
Такие штуки как 100 лучше выносить в константы

2021-05-03 09:16 UTC, IgorFilipovich commented on src/main/kotlin/by/dismess/core/dht/DHTImpl.kt
> +                newBuffer.putAll(userBucket!!.idToIP)
Оно точно не нулл?

2021-05-03 09:16 UTC, IgorFilipovich commented on src/main/kotlin/by/dismess/core/dht/DHTImpl.kt
> +            distance = newDistance
Почему мы максимизируем newDistance? Мы же не сойдемся тогда

2021-05-03 09:16 UTC, IgorFilipovich commented on src/main/kotlin/by/dismess/core/dht/DHTImpl.kt
> +    private suspend fun findNearestNodes(target: UserID): MutableMap<UserID, InetSocketAddress> {
По какому расстоянию идет ограничение соседства, т.е. на каком минимальном расстоянии берутся ноды?

2021-05-03 09:16 UTC, IgorFilipovich commented on src/main/kotlin/by/dismess/core/dht/DHTImpl.kt
> +    private suspend fun findNearestNodes(target: UserID): MutableMap<UserID, InetSocketAddress> {
И кажется функция должна сходиться не по расстоянию, а по количеству ближайших, в любом случае функция, которая ищет по количеству нужна

2021-05-03 14:14 UTC, buyval01 commented on src/main/kotlin/by/dismess/core/dht/DHTImpl.kt
> +        networkService.registerPost("DHT/Ping") {}
По новым стандартам `Dismess protocol` на `Post` запросы приходит подтверждение о том, что они дошли. Кажется, что это как раз то, что и нужно для пинга.
Ну а хэндлер на этот тег я регистрирую чисто формально, т.к. изначально на эти запросы отправляется `Approve`, а затем уже передается управление хэндлеру для выполнения каких-то задач. Задач нет - хэндлер пустой)

2021-05-03 14:16 UTC, buyval01 commented on src/main/kotlin/by/dismess/core/dht/DHTImpl.kt
> +    private suspend fun tryToSaveUser(userId: UserID, address: InetSocketAddress) {
Я этоже не англ C3, но мне кажется это симпатишным)))

2021-05-03 14:17 UTC, buyval01 commented on src/main/kotlin/by/dismess/core/dht/DHTImpl.kt
> +    private fun getBucketWithUser(userId: UserID): Bucket {
Да, норм замечание, все учту)

2021-05-03 14:18 UTC, buyval01 commented on src/main/kotlin/by/dismess/core/dht/DHTImpl.kt
> +        while (findIterations < 100 || usersBuffer.size > 1) {
Ну я пока прост на глаз поставил, т.к. непонятно сколько итераций вообще необходимо, но это однозначно нужно, чтобы обойти проблему, что мы знаем только одного чела, а ищем кого-то другого.

2021-05-03 14:21 UTC, buyval01 commented on src/main/kotlin/by/dismess/core/dht/DHTImpl.kt
> +                newBuffer.putAll(userBucket!!.idToIP)
Двумя строчками выше я пропускаю `respons`ы, которые `null`

2021-05-03 14:21 UTC, buyval01 commented on src/main/kotlin/by/dismess/core/dht/DHTImpl.kt
> +            distance = newDistance
Оооооой

2021-05-03 14:22 UTC, buyval01 commented on src/main/kotlin/by/dismess/core/dht/DHTImpl.kt
> +            distance = newDistance
Да, там наоборот нужно)))

2021-05-03 14:22 UTC, buyval01 commented on src/main/kotlin/by/dismess/core/dht/DHTImpl.kt
> +            distance = newDistance
Кодить ночью вредно для проекта)

2021-05-03 14:24 UTC, buyval01 commented on src/main/kotlin/by/dismess/core/dht/DHTImpl.kt
> +    private suspend fun findNearestNodes(target: UserID): MutableMap<UserID, InetSocketAddress> {
Кажется, что заранее ограничить расстояние не удастся, т.к. рандомом может так раскинуть айдишники, что их вроде в сети будет и мало, а значит почти все друг о друге будут знать, но расстояние будет гигантским

2021-05-03 14:26 UTC, buyval01 commented on src/main/kotlin/by/dismess/core/dht/DHTImpl.kt
> +    private suspend fun findNearestNodes(target: UserID): MutableMap<UserID, InetSocketAddress> {
Поэтому просто утверждается(или нет, но я почему-то в этом подсознательно уверен), что, совершая итерацию за итераций, последовательно обновляя расстояние приближения, мы за каких-то `n` итераций подберемся довольно близко к искомой цели

2021-05-03 14:27 UTC, buyval01 commented on src/main/kotlin/by/dismess/core/dht/DHTImpl.kt
> +    private suspend fun findNearestNodes(target: UserID): MutableMap<UserID, InetSocketAddress> {
Ну тут тоже спорный вопрос с тем, что как понять сколько их близко может быть. Для вполне "густой" сети может и норм, но вот на начальный этапах, когда нод прям довольно мало, то можно багов наловить и найти совсем не то,  что нужно

2021-05-03 14:28 UTC, buyval01 commented on src/main/kotlin/by/dismess/core/dht/DHTImpl.kt
> +            }
Ну да, звучит здраво

2021-05-03 14:29 UTC, buyval01 commented on src/main/kotlin/by/dismess/core/dht/DHTImpl.kt
> +            }
Сча попробую улучшить тогда

2021-05-03 14:29 UTC, buyval01 commented on src/main/kotlin/by/dismess/core/dht/DHTImpl.kt
> +            tryToSaveUser(request!!.sender, message.sender)
Оо, норм тема, спасибо, что напомнил

2021-05-03 14:43 UTC, buyval01 commented on src/main/kotlin/by/dismess/core/dht/DHTImpl.kt
> +            }
Вот я за время выполнения этого метода добавил в бакет ноду, которая нарушает количетсвенное ограничение, затем пытаюсь найти потухшие ноды и в случае, если там все живы надо по какому-то другому признаку уменьшить их количетсво

2021-05-03 14:44 UTC, buyval01 commented on src/main/kotlin/by/dismess/core/dht/DHTImpl.kt
> +            usersTable.remove(bucket)
Приму во внимание в след комите)

2021-05-03 14:45 UTC, buyval01 commented on src/main/kotlin/by/dismess/core/dht/DHTImpl.kt
> +            }
Окей, прочистим значит ~~трубы~~ бакеты в отдельном методе)

2021-05-05 22:26 UTC, IgorFilipovich reviewed
А так в целом все норм, нужны тесты и будет все круто

2021-05-05 22:26 UTC, IgorFilipovich commented on src/main/kotlin/by/dismess/core/dht/DHTImpl.kt
> +        networkService.registerGet("DHT/Store") { message ->
Не очень понятно, почему тег DHT/Store, а не DHT/Retrieve, например

2021-05-05 22:26 UTC, IgorFilipovich commented on src/main/kotlin/by/dismess/core/dht/DHTImpl.kt
> +const val STORE_COPIES = 10
Мб назвать STORE_COPIES_COUNT что-то вроде такого

2021-05-06 11:28 UTC, buyval01 commented on src/main/kotlin/by/dismess/core/dht/DHTImpl.kt
> +        networkService.registerGet("DHT/Store") { message ->
Учел

2021-05-06 11:29 UTC, buyval01 commented on src/main/kotlin/by/dismess/core/dht/DHTImpl.kt
> +const val STORE_COPIES = 10
И это тоже учел)

2021-05-10 21:50 UTC, VKuzia approved these changes
сложно, чёрт побери

2021-05-10 21:50 UTC, VKuzia commented on src/main/kotlin/by/dismess/core/dht/Bucket.kt
> +    }
может этот метод уже не особо нужен в деве?)

2021-05-10 21:50 UTC, VKuzia commented on src/main/kotlin/by/dismess/core/dht/DHTImpl.kt
> +        bucket.idToIP[ownerID] = ownerIP
можно в константу вынести правую границу

2021-05-10 21:50 UTC, VKuzia commented on src/main/kotlin/by/dismess/core/dht/DHTImpl.kt
> +
....зачем это?

2021-05-10 21:50 UTC, VKuzia commented on src/main/kotlin/by/dismess/core/dht/DHTImpl.kt
> +            pingBucket(bucket)
переменную PING_TIMER кажется уместнее переименовать в PING_INTERVAL

2021-05-10 21:51 UTC, buyval01 commented on src/main/kotlin/by/dismess/core/dht/Bucket.kt
> +    }
Согласен)

2021-05-10 21:52 UTC, buyval01 commented on src/main/kotlin/by/dismess/core/dht/DHTImpl.kt
> +
Ну тип нам по факту никакого функционала от этого запроса не надо, а только нужен Approve о том, что он дошел, поэтому там пусто.

2021-05-10 21:53 UTC, buyval01 commented on src/main/kotlin/by/dismess/core/dht/DHTImpl.kt
> +
Ну а пустой хэндлер на тэг я оставил прост, чтобы было видно наглядно, что такое фигурирует
А то прост слать в пинге запрос на тэг, который впервые всплывает, мне показалось как-то не оч

2021-05-10 21:54 UTC, buyval01 commented on src/main/kotlin/by/dismess/core/dht/DHTImpl.kt
> +            pingBucket(bucket)
Предложение принято!

2021-05-10 21:55 UTC, buyval01 commented on src/main/kotlin/by/dismess/core/dht/DHTImpl.kt
> +        bucket.idToIP[ownerID] = ownerIP
Одобряю)

2021-05-10 22:37 UTC, IgorFilipovich approved these changes

2021-05-10 22:41 UTC, merged